title: Freastro Networks
author: Gregory Hart
description: We design apps for organizing your data and simplifying common tasks.
url: "https://freastro.net"

markdown: kramdown
plugins:
  - jekyll-seo-tag

collections:
  - products

exclude:
  - CloudFormation.yaml
  - freastro-site.iml
  - Gemfile*
  - LICENSE
  - README.md
