AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys a static website
Parameters:
  RootDomainName:
    Description: Domain name for your website (example.com)
    Type: String
Mappings:
  RegionMap:
    us-west-2:
      HostedZoneId: Z3BJ6K6RIION7M
      WebsiteEndpoint: s3-website-us-west-2.amazonaws.com
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref RootDomainName
      SubjectAlternativeNames:
        - !Join ['.', [www, !Ref RootDomainName]]
      ValidationMethod: DNS
  Dns:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref RootDomainName, .]]
      RecordSets:
        - AliasTarget:
            DNSName: !FindInMap [RegionMap, !Ref "AWS::Region", WebsiteEndpoint]
            HostedZoneId: !FindInMap [RegionMap, !Ref "AWS::Region", HostedZoneId]
          Name: !Ref RootStorage
          Type: A
        - AliasTarget:
            DNSName: !FindInMap [RegionMap, !Ref "AWS::Region", WebsiteEndpoint]
            HostedZoneId: !FindInMap [RegionMap, !Ref "AWS::Region", HostedZoneId]
          Name: !Ref WwwStorage
          Type: A
  RootCdn:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref RootStorage
        DefaultCacheBehaviour:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: "false"
          TargetOriginId: RootOrigin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: "true"
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt RootStorage.WebsiteURL]]
            Id: RootOrigin
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
  RootStorage:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref RootDomainName
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
  WwwCdn:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref WwwStorage
        DefaultCacheBehaviour:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: "false"
          TargetOriginId: WwwOrigin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: "true"
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt WwwStorage.WebsiteURL]]
            Id: WwwOrigin
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
  WwwStorage:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub
        - www.${domain}
        - domain: !Ref RootDomainName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RootStorage
